language: scala
scala:
  - 2.11.8
  - 2.12.0
jdk:
  - oraclejdk8

script:
    - sbt clean coverage test

after_success:
    - pip install --user codecov && codecov

notifications:
  irc: "irc.freenode.org#cilib"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9df9c83ef091cee2f675
    on_success: always
    on_failure: always
    on_start: false
