language: scala
scala:
- 2.11.11
- 2.12.2
jdk:
- oraclejdk8
script:
- sbt clean coverage test
notifications:
  irc: irc.freenode.org#cilib
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/9df9c83ef091cee2f675
    on_success: always
    on_failure: always
    on_start: false
after_success:
- pip install --user codecov && codecov
- '[[ $TRAVIS_BRANCH == "master" ]] && { sbt publish; };'
env:
  global:
  - secure: S9K8KxBpORXNYoEUYF3c5PxlDhEKS2phW/yyKEH7EyPnKoknOojPN9qFVNJie43iWaGNS9lFQYApq2cNoShq7+RdEvRnArU0vwd9JW+tPrQw/H2v2kEPkhUJNpp9W3XsUzmxIpvItva+0sV/Qe992ldCDS6HCdlsf0/9SzTR+1aC1xCMRwIhykMUHYBMWzrmNKZRa2btZZvjvEAjDHhXX4pussbiXF0MtPzgm+/2eWJwyzegswmTBTZKvchhAmw8f1e1x+WImtq1Wp2ZrRPPWOADOgLSidu8t/YXJ5dJfcnGXQRhMC+YM1lF4Ai06bfYx4I5frWiWjJRajXhJl9ehWy0lIuH1PZculVT1/HlB2x9fDq18TMHMtDIgfkX11YofQCV9zhytjLXRfyd3YkNhel2JBx+p001wt/0NrXbMu+U1/rzWjwqjMM4lGUfygUIbRCankJ1+cG7DDKFT8yPMsDXHaNrDyeMeQS1gS8hePkqyIlZ3vA6bF/yAi/BUd4Lr2YZe/AqtQS4c6soo+AL7MQcMkZzzURd3MiZjJlPNw3z4H0OmoTNCkB+m4+mofcPQ8A6n19zOGmNEw5nHJzlWqZVhuKsbijdh4A8TiYfj14pPnif0lb4cXsXZWwMG63omY7xgFR4/ZN2AAXQsAqWDLOGHs4WQmNvIUQwkCpk8uE=
  - secure: gZEqt+NjwIjub/RGLTanJIkahRs+ugSjn8mz7HEjMkwKnPU3NIL4NSBCWI+/3ZiF96PzSqG6EZrWaLs7Qy3T8cqMZpaWnaMuZtr0Jo5bQgyyUH8o/aUEk0MHV4SGgNcAhIqXTfO8dcorBvjmK7Rpocogvyi8i29a5Ji3WR4m4UVEP+mYrO1xIn9iOrcUckFtw3lrDIIXHFYRt+wHOvkLA7Xg0IOfSCLk9UJYpcn24m5Ld1kwBd84lUtkSvo42ZN83rD7mWgjpwibyGpKiXt0pksbAOtfYBuBwqYy+wFv4tCYfl3YAHfiUwqhtrs1X0rf8sIkuMKdKLY8Sv1vlyar1xJiST6Hb4vyQBBcMA4xZ4/okYmNrYy3AxZracCmYMWUzkslHrUcIn92yQUdxpnAoKaCAL9AO6Y3mox0ZDnw9ec63sZ/RrXBvJ9md02c18uMMKgmkgOvm49KjEWdqSq47bHG3TmyTbMZkIcXykiRB3RyRfj1AQ/XGIjRidrRYZNVhIqx1XqtvUufdwmHX82KUxS8z5tfaWeu/picGDxiJB/n+j6ZfHDBqAbHRhi8dcW1xqyRw8oDOLfYVM+ML2e//k5bg5W7CMkw8EVTnq0S9eMZ6fjeZcTefDmIGQKG8Ky/8sJBsxDAnnVi7mcMtiCMImKcClnqX6A+0peGFpNZ0nA=
